language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"

before_script:
  - travis_retry composer install -d ./phing/ --no-interaction

script:
  - ./phing/bin/phpunit -c ./phing/tests/unit/phpunit.xml --coverage-text --process-isolation