version: "3.2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: ${PROJECT_PREFIX}nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    image: mysql:5.5
    container_name: ${PROJECT_PREFIX}db
    expose:
      - 3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
#    volumes_from:
#      - data

  mail:
    image: catatnight/postfix
    container_name: dev_mail
    expose:
      - "25"
    environment:
      - "maildomain=${APP_MAILER_HOST}"
      - "smtp_user=${APP_MAILER_USER}@${APP_MAILER_HOST}:${APP_MAILER_PASSWORD}"

  orocrm:
    image: hellosworldos/orocrm
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${PROJECT_PREFIX}orocrm
    links:
      - "db"
      - "mail"
      - "nginx-proxy"
    expose:
      - 80
      - 443
#    ports:
#      - "${APP_WEBSOCKET_FRONTEND_PORT}:8080"
    volumes:
      - "${HOST_APP_ROOT}:${APP_ROOT}"
      - "./phing:/opt/phing"
      - "~/.ssh/id_rsa:/home/www-data/.ssh/id_rsa:ro"
      - "~/.ssh/id_rsa.pub:/home/www-data/.ssh/id_rsa.pub:ro"
    environment:
      - APP_DB_DRIVER
      - APP_DB_HOST
      - APP_DB_PORT
      - APP_MAILER_TRANSPORT
      - APP_MAILER_HOST
      - APP_MAILER_PORT
      - APP_MAILER_ENCRYPTION
      - APP_MAILER_USER
      - APP_MAILER_PASSWORD
      - APP_WEBSOCKET_BACKEND_PORT=80
      - APP_WEBSOCKET_FRONTEND_PORT
      - APP_SECRET
      - VIRTUAL_HOST
      - SYMFONY_ENV
      - SYMFONY_INDEX_FILE
      - APP_ROOT
      - GIT_URI
      - GIT_REF
      - DEV_USER_ID
      - DEV_GROUP_ID
      - OROCRM_ADMIN_EMAIL
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - BASE_URL
      - APP_SAMPLE_DATA

#volumes:
#  dev_orocrm_cache_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_CACHE_DIR}"
#        o: bind
#  dev_orocrm_uploads_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_UPLOADS_DIR}"
#        o: bind
#  dev_orocrm_media_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_MEDIA_DIR}"
#        o: bind
#  dev_orocrm_attachment_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_ATTACHMENT_DIR}"
#        o: bind
#  dev_mysql_dir:
#      driver_opts:
#        type: none
#        device: "${MYSQL_DIR}"
#        o: bind
#  dev_postgresql_dir:
#      driver_opts:
#        type: none
#        device: "${POSTGRESQL_DIR}"
#        o: bind
#  dev_orocrm_import_export_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_IMPORT_EXPORT_DIR}"
#        o: bind
#  dev_orocrm_root_dir:
#      driver_opts:
#        type: none
#        device: "${OROCRM_ROOT_DIR}"
#        o: bind
#  dev_orocrm_bundle_dir:
#      external: true
